import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import TopNav from '@/components/top-nav'
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" spellCheck="true">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopNav />
        {/* <header className="bg-gray-350 text-white p-4">
          <nav className="container mx-auto flex items-center justify-start space-x-4">
            <Link href="/" className="hover:underline">
              Home
            </Link>
            <Link href="/auth/signin" className="hover:underline">
              Sign In
            </Link>
            <Link href="/user-info" className="hover:underline">
              User Info
            </Link>
            <Link href="/todos" className="hover:underline">
              Todos
            </Link>
            <Link href="/todos2" className="hover:underline">
              Todos 2
            </Link>
          </nav>
        </header> */}
        <main>{children}</main>
      </body>
    </html>
  )
}
